return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    require('nvim-treesitter').install {
      'bash',
      'c',
      'cmake',
      'css',
      'git_config',
      'dockerfile',
      'go',
      'gomod',
      'gosum',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'python',
      'php',
      'phpdoc',
      'rust',
      'sql',
      'toml',
      'tsx',
      'typescript',
      'yaml',
      'zig',
    }
  end,
}
